# image:
#  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install --upgrade pip
      pip install --upgrade pandas numpy matplotlib boto3 awscli sagemaker pickleshare
  - command: |
      gp open index.ipynb

ports:
  - port: 8080
    visibility: public
    onOpen: ignore

vscode:
    extensions:
        - ms-toolsai.jupyter
        - ms-python.python
