# image:
#  file: .gitpod.Dockerfile

tasks:
  - init: echo "Preparing your Jupyter environment..."
  - command: >
      gp open index.ipynb

ports:
  - port: 8080
    visibility: public
    onOpen: ignore

vscode:
    extensions:
        - ms-toolsai.jupyter
        - ms-python.python
